owenashurst/agar.io-clone

- index.html
- package.json
- server.js
I've changed the identation on both server.js and index.html to 4 spaces. They weren't normalized so the source readability was very low. Also made some changes to make the code look prettier as a whole. Game functionality hasn't changed at all.
> Improve code readability

- README.md
Fixed several typos and made it simpler to understand.
Also added some badges for the project, including the live demo @D3VONT3CH posted at #10.
> Improve README.md quality as a whole.

- client/js/app.js
- server/server.js
Changed playerID/foodID to ID.
> minor find index and player refactor

- client/js/app.js
> forgot to rename one id

- client/index.html
> socket.io-client can by served by socket.io

- client/js/app.js
- server/server.js
gameWidth = screenWidth * 3
gameHeight = screenHeight * 3
The player figure will keep staying in the middle of screen. When it moves, other objects will change position according to it.
> Enlarge arena size and change player moving method

- server/server.js
I commented a unnecessary line that flooded in my console .
> Unnecessary log

- package.json
- server/server.js
fixed merge conflicts, added Ariamiro and giongto35 to contributors
https://github.com/huytd/agar.io-clone/pull/42
all credits to @giongto35
> Player moves slower [...]

- server/server.js
min x = 0
min y = 0
max x = player.gameWidth
max y = player.gameHeight
> Chroot player in gamearea

- client/js/app.js
- package.json
This added a grid to the canvas, it also gave the main variable the right path to server.js
> added grid as per issue #57

- .travis.yml
Needs to be activated for this repository on https://travis-ci.org/
> Added travis support

- server/server.js
> Cell is moving slower when cursor is near cell

- README.md
This PR fixes some minor grammar errors in the README.
> Minor english grammar fixes in README

- client/css/main.css
Improve the menu with borders and webkit effects
> Update menu css

- server/server.js
> Correct random range function

- .gitignore
- package.json
- server/config.dist.yml
- server/server.js
I think it makes more sense to have an isolated config file, we're then allowed to play around with game configs without changing code, also it's more readable as you know exactly what configs can be altered since it's everything in one single place.
> Move configuration from script to YAML file

- client/css/main.css
- client/js/app.js
Makes more sense for incoming messages to rise from the input box.
> Make chat more intuitive

- client/js/app.js
- server/server.js
Generate a hue for each player when they connect. Use it to render them for the rest of the game.
> Adds random colors to the server

- server/server.js
> add removePlayer method

- .gitignore
- .jshintignore
- gulpfile.js
- package.json
> Build system

- client/js/app.js
Using parametric equation of a circle to draw circular food with a fixed number of sides.
> Adding polygonal food shapes

- client/js/app.js
- gulpfile.js
- server/server.js
> Fiexed jshints errors

- client/js/app.js
- server/server.js
This is merging four emits when only two are required.
> Merging four to two continuous emits

- client/js/app.js
- server/server.js
Stop the food from being perfectly aligned.
> adds random rotation to each food

- client/js/app.js
> use single quotes

- client/js/app.js
> use the correct indent

- server/server.js
> use spaces as indent

- client/js/app.js
> Fixed spiky 4s

- gulpfile.js
- package.json
> Added browsersify

- README.md
> updated screenshot to reflect current state of the game

- client/js/app.js
- server/server.js
Changing playerSendTarget to 0 reduces the bytes transfer just enough so that it doesn't lag for me, thought I'd share this update. Also fixes issue #60
> Reducing Bytes transfer per heartbeat / issue #60 resizing window

- client/js/app.js
- server/server.js
I made the server have to specifically ask for the foods to be updated if they are eaten or another person joins etc. and the players who do not move do not send updates, only receive.
> Stop updates for food/users if not changed.

- client/js/app.js
- server/config.yml
Fixes https://github.com/huytd/agar.io-clone/issues/135 and makes cell size closer to real cell.
> Make Food Size and Cell closer to real Agar / Remove Food Width/Height unused.

- client/js/game.js
- gulpfile.js
- server/server.js
also we should start thinking about merging es6-refactor to master
all patches since this branch should be added
> Fixed movement

- client/js/app.js
Newb here, I made a simple border function. This is my first pull request. I spent some time trying to make the lines end at the corners but decided to keep it simple. I think it would be nice to be able to toggle these borders. Thanks for creating this project.
> Visible borders

- client/js/app.js
Increased game canvas to *10 instead of *3 and added help message to tell people about available commands.
> Increased game canvas and added help message

- client/js/app.js
- server/config.json
- server/server.js
Probably not the best way of fixing it but stops crashes for now.
> Fixing #151 Crash / Add admin commands - Password and kick so far / Adding death screen

- package.json
- server/server.js
Simplified a few loops using map/reduce
Now using SAT.js (Separating Axis Theorem) based hit-detection. 
- This should have the biggest performance benefit during player/player collision checking (see my ES6 branch for a buggy test implementation)
- should be compared with a sparse quadtree-based algo to determine which is the most performant.
> Separating Axis Theorem hit detection and map/reduce optimisations

- server/server.js
Reason:
http://jsperf.com/while-vs-map-findindex/2
> remove the map code and add the removed while loop

- server/server.js
Note 1: Use single quotes
Note 2: Use the same indent as is used in the code. See .editorconfig
Note 3: Use the same if else statements
Note 4: Remove the space in anon functions between function and paranthesis
> clean up messy code

- client/css/main.css
- client/index.html
- client/js/app.js
I added a settings button and an option to toggle borders. I figure we can add other features as we go. Borders are disabled by default.
> Add settings button and border option

- README.md
- manifest.yml
Created manifest.yml configuration for Bluemix servers.
Updated README with the deployed agar.io-clone Bluemix servers.
> Updated with Bluemix configurations and servers

- client/js/app.js
Decreased max speed from 20 to 7
> Decreased max speed so it's like Original Agar.io

- client/css/main.css
- client/js/app.js
- server/server.js
This is the same as #153 but fixes the merge conflicts.
> Fix merge conflicts for pull request #153

- client/js/app.js
> Uncaught ReferenceError: i is not defined

- client/js/app.js
Mass Mode now viewable via the ingame command "-mass".
The Mass is now easily visible at the end of the Player's name.
See more: https://github.com/huytd/agar.io-clone/issues/196
> Add View Mass Mode ( #196 )

- server/config.json
- server/server.js
Dear Developers,
i think that chat logging is a nice feature, what do you think about this?
Some information about this:
Chat can be easily logged via the server console.
Settings can be configurated in "server/config.json".
The Default is 'Zero', that means deactivated!
To highlight the chat conversation, the Output in the server console begins with "[CHAT]".
Hope it helps,
Simon.
Example:
> Add logChat

- server/config.json
- server/server.js
Added the option to change the log base of the slowDown logarithm. The initial speed will not be affected. 
Mass is on the horizontal-axis:
Previously : (log2)
I figure if we can adjust it easily now we can eventually fine tune it and remove it from the config file.
> Add SlowDownLog in config file to address issue #204

- .jshintrc
- client/css/main.css
- client/index.html
- client/js/app.js
- gulpfile.js
- server/server.js
* CSS is now a bit more readable (will add some tools for css on later pr's)
* client code passes jslint
* server code passes jslint
* Removed unnecessary white spaces from js
* Made js more readable and a bit more consistent
> Improved code readability and fixed issues pointed out by jslint

- client/js/app.js
- server/server.js
I tried to replicate the effect of pressing against a boundry in agar.io. Now when you approah a border your blob will change shape and wiggle a little on the side that's touching the border. There are probably more pressing issues but I was having fun with this one. It doesn't work in corners or with enemies. I'll let you decide if you want to merge it or not.
> Added border collision effect

- server/config.json
- server/server.js
The config item "slowDownLog" wasn't working properly. I renamed it "slowBase" and it should work just fine.
> Fix bug and decreased slow rate. Issue #204

- client/css/main.css
- client/index.html
- client/js/app.js
- package.json
- server/server.js
- Cells collide with walls based on radius, not mass
- Players should die correctly
- Chatbox input automatically selected when game starts
- Respawning should work
- Fixed critical security vulnerability allowing clients to access admin password, since the server **sent the entire config, most of which was unused, to the client LOL**
- Organized code formatting
- Added self as contributor, added repository field to package.json
- Added some transitions to elements
- Server-side username validation, in case client edited JavaScript to disable it
- Applied player-squish-against-wall-and-wiggle rendering to enemies
- Added border toggle command, and optional on/off args to mass command
> Batch of random fixes

- server/config.json
- server/server.js
Place the food **more uniformly** in the game, so everyone has *more or less* the same probability to eat a food and grow.
I've made this configurable by ```"foodUniformDisposition": true``` in ```config.json```
To make this more accurate and regular increment ```numberOfCandidates``` on https://github.com/bigfoot90/agar.io-clone/blob/uniform-disposition/server/server.js#L41
I've applied the same algorithm to the user, so when a new user connects it is placed away from others.
To enable this set ```"newPlayerInitialPosition": "farthest"``` in ```config.json```
**Before**
**Now**
> Food placed uniformly

- package.json
As you suggested after https://github.com/huytd/agar.io-clone/pull/223
I'm adding myself as a contributor.
> Adding bigfoot90 as contributor (Thanks to @IgorAntun)

- client/js/app.js
This is similar to my last pr but with a complete circle. The advantage of this is that the circle will react to corners and in the future we can add a wiggle function that will modify all the points. The amount of points drawn through is directly related to mass. I still haven't applied this to the enemy player but I'll do that next if this is merged.
> Draw circle different

- gulpfile.js
- server/lib/util.js
- server/server.js
In this PR, shared utilities (such as Math.log, randomPosition) have been moved into `lib/util.js` and are imported into the main server.  The gulpfile has been changed appropriately to build utilities as they change.
> Move shared utilities into lib/util.js

- client/js/app.js
- server/config.json
- server/server.js
I made it look and feel more like agar.io. Changed the grid and background color and the player size a little.  Players wont lose mass when they haven't eaten anymore. I added mass to the food object in server.js(I also made it slightly random). I adjusted the speed a little. I also changed the name of the "contain" function to "valueInRange".
> Players don't lose mass below 10, cosmetics, add random mass to food object.

- server/lib/util.js
- server/server.js
Moving ```uniformPosition``` function to ```util.js```
> Moving uniformPosition function to util.js

- server/lib/util.js
- server/server.js
Moving ```validNick``` function out to ```util.js```
> Moving validNick function out to util.js

- server/server.js
Have fixed ```balanceMass``` function to correctly calculate how many foods add or remove.
I can also write tests to prevent reverts.
Waiting for feedback.
> Fixed balanceMass function

- client/js/app.js
Removed unused ```massToRadius``` function on client
> Removed unused massToRadius function

- server/lib/util.js
- server/server.js
Moved ```findIndex``` and ```randomColor``` function out to ```util.js```
> Moved findIndex and randomColor function out to util.js

- server/server.js
Brought back in the overlap when eating another player.
> Fixed player eating player collision

- package.json
- test/util.js
In this PR:
- Added mocha/chai as dev-dependencies
- `npm test` runs mocha
- added a few tests for `util.js`
> Util.js unit tests written in mocha/chai

- gulpfile.js
And subsequently, Travis build.
No extra dependencies introduced.
> Linting fails gulp build

- client/js/app.js
In this PR, chat has been condensed into a single class.  The callbacks for chat functions have also been cleaned up significantly.
> Coalesce chat commands into ChatClient class

- client/js/app.js
- server/server.js
I changed the enemy rendering to be like drawPlayer. 
The player/enemy with larger mass will come out on the foreground.
mass loss won't drop below 10.
Players who haven't eaten won't be checked for collisions.
> Update enemy rendering, players who haven't eaten cannot be eaten again, large mass blobs on top.

- quadtree.js
- src/server/server.js
I'm using a fork of [silflow's quadtree](https://github.com/silflow/quadtree-javascript). I wasn't sure where to put the quadtree.js file. As far I know it's working. Please review.
> My attempt at implemtenting a quadtree

- README.md
> Updated Server List

- src/client/js/app.js
- src/server/server.js
Change the mass under the name of the cell
> Change the mass under the name of the cell

- src/client/index.html
- src/client/js/app.js
- src/server/server.js
Submitting for community review.
> Slightly more readable fonts and viewport meta fix

- src/client/css/main.css
- src/client/index.html
- src/client/js/app.js
- src/server/server.js
-Cambio en la formas y colores del alimento dejando si uso la funcion randomColor
-Agrega margen al leaderboard
-Correccion error en chat con usuarios que tienen el mismo nombre
> Cambio en la formas y colores del alimento

- config.json
- src/client/js/app.js
- src/server/server.js
-Correction in the dark theme
-Added the ability to split #26
-Once divided still cant join
> Added the ability to split #26

- src/server/server.js
if player removes limit in html, other player will still only get the first 35 characters
> added char limit in server-sided

- src/client/index.html
kinda ridiculous when someone is called 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
> nickname limit

- src/client/js/app.js
even html edit cant pass it now
btw, how do i write stuff to the same pull request? different files and stuff?
> Added nickname limit server-sided

- src/client/css/main.css
- src/client/index.html
- src/client/js/app.js
- src/server/server.js
Added a "spectate" mode
So that one can see the whole playground
> added spectacle mode

- src/client/js/app.js
Resolves feature #47
Pressing the arrow keys will now allow the the player to move in 8 different directions, at max speed.
While the user is using the keyboard to move, the mouse input will be ignored until no arrow key is being held.
Using "w" or "space" while in keyboard mode will fire in the current direction and not in the direction of the mouse (this could be changed in the future if needed by storing the mouse position and using it to fire instead of the current "target").
Has not been tested together with touch input, but it should work properly.
> Using arrow keys to control the player

- src/client/js/app.js
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/354%23issuecomment-161735896%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/354%23issuecomment-161735896%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks%20for%20fixing%20it%21%22%2C%20%22created_at%22%3A%20%222015-12-03T18%3A12%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/IgorAntun%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' …
> Little fix in cell name

- config.json
- gulpfile.js
- src/client/js/app.js
- src/server/lib/util.js
- src/server/server.js
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/361%23issuecomment-166231688%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/361%23issuecomment-166671632%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/361%23issuecomment-166231688%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22It%20worked%20.%5Cr%5CnI%20think%20you%20should%20change%20fill%20and%20stroke%20%3A%20%5Cr%5Cn%5Ct%5C%22fill%5C%22%3A%20%5C%22%232EE62E%5C%22%2C%5Cr%5Cn%5Ct%5Ct%5C%22stroke%5C%22%3A%20%5C%22%233f3%5C%22%2C%5Cr%5CnThats%20the%20colors%20i%20captured%20inspecting%20the%20original%20game%20.%5Cr%5CnI%20could%20not%20sucessfully%20explode%20collidin …
> Implement spawn of viruses

- config.json
The viruses follow the usual green colour scheme.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/363%23issuecomment-166735928%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/363%23issuecomment-166735928%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Just%20changed%20from%20an%20invalid%20hexadecimal%20integer%20which%20was%20suggested%20by%20another%20user.%20Had%20to%20use%20a%20valid%20one.%22%2C%20%22created_at%22%3A%20%222015-12-22T21%3A37%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/13650994%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Incognitov%22%7D% …
> Updated colour scheme

- src/server/server.js
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/IgorAntun%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/364%23issuecomment-166806147%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22That%20looks%20nice%2C%20thanks%21%20%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-12-23T05%3A13%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/IgorAntun%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22htt …
> Nicer console messages (Organized)

- src/client/js/app.js
Improved typography in app.js, as well as one or two minor bug fixes in chat.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/IgorAntun%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/365%23issuecomment-167047716%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%2B1%20because%20code%20readability%20matters.%20Thanks%21%5Cr%5Cn%5Cr%5Cn%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-12-24T06%3A06%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//githu …
> Typographical improvements and bug fixes

- config.json
- src/client/js/app.js
- src/server/server.js
- Fixed issue #25
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/IgorAntun%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/370%23issuecomment-172610120%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks%20for%20the%20contribution%21%20%3A%29%5Cr%5Cn%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222016-01-18T18%3A12%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/IgorAntun%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2 …
> [issue25] Added virus detection

- README.md
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/huytd%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/613943%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/373%23issuecomment-172971886%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-19T20%3A10%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/613943%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/huytd%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Pull%20f534b6ddd91bd9bafa465c763c0cff6dcf046cc4%20README.md%209%22%3A%20%7B%22ht …
> Updated to suit the latest changes

- src/client/index.html
- src/client/js/app.js
I'm still dazzled by why this fixes the issue, but with the recent sound effect addition it caused the split button to stop working. Doing the following fixed it, somehow! But I think the important part is that it is fixed now. ;)
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/IgorAntun%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/376%23issuecomment-173664616%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Well%2C%20that%27s%20weird.%20But%20hey%2C%20it%20works%20%3A%29%5Cr%5Cn%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-21T18%3A26%3A34Z%22%2C%20 …
> Sound effects fix (for mobile)

- config.json
- server/index.js
- server/player.js
extract some stuff into a Player class and make some better use of es6 syntax in a few places. I think this makes the code easier to read.
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/392?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/392'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> more es6 refactorings of the server code

- src/client/index.html
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/394%23issuecomment-189956126%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/394%23issuecomment-189956126%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22an%20issue%20happened%20on%20heroku%20because%20of%20https%2C%20so%20i%20fixed%20it.%22%2C%20%22created_at%22%3A%20%222016-02-28T22%3A14%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6854678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ozdemirr%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …
> jquery source fixed for protocol free[https-bug]

- config.json
- server/index.js
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/408?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/408'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Added min mass loss, closes #403

- gulpfile.js
- package.json
**Need to review**
---
There are many contributors has joined and help the project now (many thanks to all of you, guys!)
But the `contributors` section in `package.json` has been stopped updating for a long time. 
In the beginning, we asked contributors to add their name into this section manually, but time goes on, some of the new contributors didn't know about that so they didn't put their name in. 
I created a new `gulp` task to do this automatically. Run it with: 
```
gulp contributors
```
This will call some Github API and update `package.json` 
Didn't tested this code yet because I'm now reaching the call limit of the API, so I pushed it here, somebody please help me test the output `package.json` if it has any damage or not.
I will be able to test the API again at next 8 hours …
> Add gulp task to automatically add contributors to package.json

- gulpfile.js
- package.json
This addition allows for the creation of a TODO.md file upon running "gulp todo" or "gulp build". This utilizes the package "gulp-todo" to generate the file. This is useful to keep track of what changes need to be implemented after running a build. This is in response to issue #368.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/420%23issuecomment-221407906%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/420%23issuecomment-221407906%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22That%20looks%20awesome%2C%20thank%20you%21%22%2C%20%22created_at%22%3A%20%222016-05-24T21%3A32%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20 …
> Functionality to create 'TODO.md' file on build

- .travis.yml
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/427?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/427'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> also run test on nodejs v4/6 LTS

- package.json
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/428%23issuecomment-223585964%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/428%23issuecomment-223585964%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Nice%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-03T13%3A58%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10373452%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/RLEXBuilding%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' …
> bump nodejs/npm dependencies

- src/server/server.js
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/432?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/432'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Quick'n'Dirty Fix for #413

- src/client/js/app.js
Small change. Not really important but should be changed I think.
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/438?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/438'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Variable Name adjusted

- package.json
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/441?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/441'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Add sync-request to production dependencies for Heroku deployment

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
Hi, thank you very much for your work on this game!
I plan to make it playable by robots, so I can do a little competition amongst developers in my research group, just for fun. I wanna do this changing as little as possible, to maybe both ways can coexist. The first change I made is this Docker support. Nothing much, but I really like Docker :)
Bye.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/443%23issuecomment-233773724%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/443%23issuecomment-233773724%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Awesome%21%20Thank%20you%20for%20your%20contribution%20%3A%29%22%2C%20%22created_ …
> Add Docker support

- TODO.md
- src/client/js/app.js
- src/client/js/chat-client.js
- src/server/server.js
fix "ping" and/or "pong" reserved events.
see: https://github.com/socketio/socket.io/issues/2414
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/454?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/454'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> fix "ping" and/or "pong" reserved events

- gulpfile.js
- package.json
- src/client/js/app.js
- src/client/js/canvas.js
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/459%23discussion_r78989215%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/459%23issuecomment-247361382%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/459%23issuecomment-247361382%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22BTW%20you%20don%27t%20have%20to%20make%20a%20new%20branch%20and%20PR%20for%20every%20commit%22%2C%20%22created_at%22%3A%20%222016-09-15T15%3A27%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2415829%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/abalabahaha%22%7D%7D%5D%2C%20%22title% …
> fix some bugs

- src/server/server.js
The password given in config.json was never used
> Use the password from config.json

- src/client/index.html
> Delete reference to "virtualjoystick.js"

- src/server/lib/util.js
> comment typo

- src/server/server.js
Fixes: #557 
First, I changed the _sender value to currentPlayer.name to prevent player being able to identify sender as anyone other than themself, which fixes the xss vulnerability and is in of itself a vulnerability.
Then, I checked to make sure that currentPlayer.name cannot be used maliciously in the same way as _sender, which is currently prevented by the validNick function, but since it's not clear the purpose of validNick I decided it's best to sanitize the name separately, in case validNick is changed in the future.
Before:
After:
And server results of that action:
> Fix xss vulnerability
