server/server.js
server.js only takes into account when bigger cells are going into "you" not when "you" are going into them, this fixes that.
=> Update server.js to count people going into bigger cells

client/js/app.js
This pull request fixes #44.  Mouseout event stops player motion until the canvas detects mouse movement again.
=> Stop player motion when the mouse leaves the canvas

client/css/main.css, client/index.html, client/js/app.js
Fixes #140.  Enforces players to use alphanumeric nicknames.  Underscores and spaces are allowed, as well the empty nickname.  A screenshot is shown below.
=> Enforce alphanumeric nicknames

client/js/app.js
Add the logic for a very rudimentary (ugly) border.
Hoping for help from a design guy :P
=> Add rudimentary border and increase squares' size for better performance

client/css/main.css, client/index.html, client/js/app.js, server/config.json, server/server.js
<b>I need feedback on the leaderboard and how to make it look better</b>
- Fix #220 
- Fix #217 by having the server process movement in a tick loop instead of waiting for client heartbeat
- Server kicks client if it has not received a heartbeat within the interval specified in the config (default 5000ms) (fixes bug where some clients with bad connection don't tell the server they disconnected)
- Added a option to toggle continuity (satisfy both #44 / #215) , because some people want it to move even after the window loses focus while some don't
- Somewhat implements a leaderboard, partially resolving #119 , but it sorts the users array once a second instead of using a balanced tree
- Moved mass balancing to once-per-second loop with leaderboard, as those don't necessarily need to be …
=> Some more misc stuff

server/server.js
If you set ```foodMass=2``` or greater all foods are removed and then re-added resulting in a blinking screen.
=> [bugfix] Food mass different from 1

client/js/app.js
```massToRadius``` is used twice by ```drawFood``` (lines [L156](https://github.com/huytd/agar.io-clone/blame/master/client/js/app.js#L456) and [L476](https://github.com/huytd/agar.io-clone/blame/master/client/js/app.js#L476))
=> [bugfix] massToRadius used twice by drawFood

server/config.json, server/server.js
- Every second, each player loses a percentage mass. The percentage is calculated as the mass loss ratio in the config divided by 1000 (#224)
- Introduces a upper food limit, which limits the food rather than the mass. The global mass limit is still in place (#225)
- Server sends integer mass
- It now balances mass when players aren't on, since the board would be devoid of/filled with too much food if nobody was playing before somebody logged on
=> #224, #225, and a misc. tweak or two

client/js/app.js, server/lib/util.js
This **PR** replaces https://github.com/huytd/agar.io-clone/pull/235 and https://github.com/huytd/agar.io-clone/pull/239 beacause they come together.
Now renders food and players using ```radius``` given from server.
=> Fixed food and players rendering

gulpfile.js, package.json
This PR adds `gulp-uglify` for JS source compression.  This results in a 50% smaller file for app.js.  Here are the results on my machine:
**Original**
**Minified**
=> Added uglify for src compression

client/js/app.js
Fixes a bug with the player mass chat toggle.  Typing `-mass` in the chat now has the expected behavior of toggling the mass view on and off.
=> FIX: mass toggle actually changes player name text

client/js/app.js
This PR fixes a bug where dark mode did not respond on the first `-dark` command toggle.
=> FIX: dark mode responds on first command

gulpfile.js
In the "Move all source files to src directory." change the move-client
task wasn't updated to include src/ in the paths.
=> Fix paths in move-client rule to include src/

package.json
A not-so-smart-but-works fix for #285 and logic
Why are they "development dependencies" if they are actually necessary for end users to run the project?
Side note: Heroku deployment now works.
=> Dev deps are actually necessary lol

src/client/js/app.js
Fixes #301 
It is still possible to use **TAB** key to access chat quickly.
Tested on desktop, using the latest Google Chrome, Mozilla Firefox and Microsoft Edge (as of 28/09/2015).
=> Change starting input focus to game canvas

README.md
This is so that a commit doesn't have to be made every time someone feels like updating the list of live demos.
=> Refer Live Demos in README to Live Demos in wiki

src/client/js/app.js
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/360?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/360'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix typo in command recognition error message

config.json, src/client/js/app.js
- fixed issue #371
- User for now always renders on top of viruses. Later we can implement a way to change order based off of size.
- Updated the virus color back to green with a more definite border.
- ```"fill": "#33ff33",
"stroke": "#19D119"```
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/372?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/372'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> [issue371] Updated render order of viruses

src/client/index.html
Updated jQuery from 2.1.4 to 2.2.0, which has a variety of bug fixes and improvements. Removed jQuery UI which is not necessary for this project.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/382%23issuecomment-177258131%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/382%23issuecomment-177258131%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks%20%3A%29%22%2C%20%22created_at%22%3A%20%222016-01-30T17%3A35%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/IgorAntun%22%7D%7D%5D%2C%20%22title%22%3A%20%22Gener …
=> Updated jQuery and removed useless reference

server/index.js
I forgot to add `return true` to the `check()` function in PR #409:
> Iterating over objects continues as long as there are remaining objects and the callback function returns true. If the callback does not return true, the iteration is interrupted.
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/411?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/411'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fixed collisions

src/client/js/app.js, src/client/js/canvas.js, src/client/js/chat-client.js, src/client/js/constants.js
In this pull request, I have moved the Chat Client and Canvas objects and their respective functions into their own files, called "chat-client.js" and "canvas.js". This is in contrast to the current model with both of these objects defined in the global "app.js" code. I think that doing this will make it easier for incoming developers to be able to work with the current code as well as for us to test functionality in specific parts of the project without breaking others. 
I plan to refactor more of the code and hopefully will be able to successfully break down the project into very simple components (game logic, chat client, game canvas, controls, relevant constants, etc.). I think overall this would make the project more welcoming to developers who want to use the code. 
Please let me …
=> Added Chat Client and Canvas modules

src/client/js/canvas.js
Variable got the wrong name, so the if condition never got to true and you couldn't split/feed
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/439?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/439'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Bugfix for Keyboard Controls

src/client/js/app.js
Hi, I'm trying to make the spectator mode work properly.
The center of view (player coordinates) was not being set properly, but to a random position on the game area. Therefore the spectator could only see a part of the game. Fixed that by updating the player coordinates to the center of the screen on the 'resize' event callback.
This pull request resolves issue #444.
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/446?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/446'><img …
=> Fix spectate mode only showing a part of the game

config.json, src/server/server.js
It's practical to be able to define the host in the configuration file, like the port.
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/484?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/484'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Set the host in the configuration file

src/client/css/main.css
Added `overflow:hidden` to fix the positioning issues caused by the leaderboard update.
Fixes: #515, #520
=> Hide overflow in body

src/server/map/player.js
Whenever things got exciting, the server would crash on this line.
I believe it is a cell merge concurrency issue where the player cell to be checked is no longer there. A simple null check has allowed us to play long games without crashing.
=> Add null check to eat check

README.md
I checked the wayback machine, and it seems like the live version of the game has not been live for a couple years. We should remove the url to not confuse readers.
Resolves #556
=> remove "live" url from README

TODO.md, src/server/server.js
Based on TODO.md, log the incorrect password that user attempted along with existing message to the console (I don't know why the original said line 364, I assume a lot of refactoring has gone on since 2017 ;p)
=> Log incorrect password
